version: "3"
services:
    #PHP Service
    app:
        image: myfirstproject:latest
        container_name: myfirstproject
        restart: unless-stopped
        networks:
            - webservernetwork

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserverapp
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - webservernetwork

#Docker Networks
networks:
    webservernetwork:
        driver: bridge
