# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
strategy:
  matrix:
    linux:
      OperatingSystem: 'ubuntu-latest'
    macos:
      OperatingSystem: 'macos-latest'

pool:
  vmImage: $(OperatingSystem)

steps:
- script: echo job running on $(OperatingSystem)
  displayName: 'Run a one-line script'

